name: Deploy Backend Docker Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'render.yaml'
      - '.github/workflows/deploy-backend.yml'

concurrency:
  group: backend-docker-${{ github.ref }}
  cancel-in-progress: true

env:
  BACKEND_DIR: backend

jobs:
  build:
    name: Build backend container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '${{ env.BACKEND_DIR }}/package-lock.json'

      - name: Install backend dependencies
        working-directory: ${{ env.BACKEND_DIR }}
        run: npm ci

      - name: Generate Prisma client
        working-directory: ${{ env.BACKEND_DIR }}
        run: npx prisma generate

      - name: Build Docker image
        run: docker build -t hamlet-backend ${{ env.BACKEND_DIR }}

  deploy:
    name: Trigger Render deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          if [ -z "$RENDER_API_KEY" ] || [ -z "$RENDER_SERVICE_ID" ]; then
            echo "RENDER_API_KEY and RENDER_SERVICE_ID secrets are required." >&2
            exit 1
          fi
          curl -fsS -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -d '{"clearCache": true}'
